### PR TITLE
Add tooltip example

### PR DESCRIPTION
**Pull request by veroo-m**
This PR adds the example created for https://pspdfkit.zendesk.com/agent/tickets/119175 to awesome-pspdfkit

### CODE REVIEW

**Review by ChrisixFlash — CHANGES_REQUESTED** [review]
Probably wouldn't hurt to either create a quick redaction annotation in the example or at least adding the toolbar items so people can actually check this in there?

**Review by eli7pm — COMMENTED** [review]
LGTM

**Review by eli7pm — APPROVED** [review]

**Comment by eli7pm** [comment]
> @eli7pm why did you change the playground link?

@veroo-m to update the example with a selected Redaction Annotation. I added it to the description.

**Comment by veroo-m** [comment]
> @veroo-m to update the example with a selected Redaction Annotation. I added it to the description.

@eli7pm Thank you for improving the snippet. Generally, it's bets not to push commits on others PRs unless previously agreed on. If you really need to, just make sure to give the PR owner a heads up smtg like 
```
Hey @author, I've added a commit to your PR that [brief description].
This addresses [specific reason].
```

**Review by ChrisixFlash — APPROVED** [review]
LG, thanks!

**Comment by eli7pm** [comment]
> > @veroo-m to update the example with a selected Redaction Annotation. I added it to the description.
> 
> @eli7pm Thank you for improving the snippet. Generally, it's best not to push commits on others PRs unless previously agreed on. If you really need to, just make sure to give the PR owner a heads up smtg like
> 
> ```
> Hey @author, I've added a commit to your PR that [brief description].
> This addresses [specific reason].
> ```

@veroo-m awesome! Thanks. I was added as a reviewer for this PR, that's why I thought I could change things, and since this was waiting for a while, I looked at this and said "why not?". I see we have different working styles, so I'll make sure to ask you first moving forward.

**Comment by veroo-m** [comment]
@eli7pm this is not working styles, this is best practices when working on PRs it helps maintain clean ownership and accountability.

**Pull request merged**
